### ISSUE TITLE
Mapping: conflict with NERDCommenter

### ISSUE THREAD

**Issue by yujiaao100** [WolfgangMehner/lua-support#1]
Mapping already in use: "<LocalLeader>cb", mode "n", command:
  <Plug>NERDCommenterAlignBoth
Mapping already in use: "<LocalLeader>cb", mode "v", command:
  <Plug>NERDCommenterAlignBoth

when open lua file how to fix this?

**Comment by yujiaao100** [comment]
I set mapleader to  temporary fix it 
let g:Lua_MapLeader = '#'    
There may be a better way after I learn more about vim

**Comment by WolfgangMehner** [comment]
For one, the map will not be overwritten once you read the warning message (Mapping already in use: ...)

You can set the map in the templates library. Edit it via the map `\ntl` (or `#ntl`, if you set the mapleader like this) or the menu entry `Lua -> Snippets -> edit local templates`. In the file `comments.templates` you while find the definition of the map:

    == Comments.shebang == start, map:cb ==
    #!|LUA_INTERPRETER|<CURSOR>
    == ENDTEMPLATE ==

The map is set by the option `map:cb` and can be changed right there.

**Comment by yujiaao100** [comment]
By changing localleader ,I found "Comments.shebang" in  comments.templates which cause the problem. so I  commented it.Thank you
